name: Node CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U myuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: localhost
      DB_PORT: "5432"
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
      JWT_SECRET: test-secret

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci

      - name: Wait for Postgres
        shell: bash
        run: |
          for i in {1..60}; do
            (echo >/dev/tcp/localhost/5432) >/dev/null 2>&1 && echo "Postgres is up" && break
            echo "Waiting for Postgres..."
            sleep 1
          done

      - name: Seed DB
        run: node setup-database.js

      - name: Run tests
        run: npx jest --runInBand --passWithNoTests
